"""initial

Revision ID: a8f936dd094f
Revises: 
Create Date: 2026-09-30 22:25:47.314123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f936dd094f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mandis',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('coords_source', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_mobile'), 'otp_challenges', ['mobile'], unique=False)
    op.create_table('tts_cache',
    sa.Column('cache_hash', sa.String(length=200), nullable=False),
    sa.Column('audio_b64', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('village', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('crops', sa.JSON(), nullable=False),
    sa.Column('crop_details', sa.JSON(), nullable=False),
    sa.Column('farm_size_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_cost_per_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('price_alerts', sa.Boolean(), nullable=False),
    sa.Column('weather_alerts', sa.Boolean(), nullable=False),
    sa.Column('primary_mandi', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('home_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('home_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('price_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mandi_id', sa.String(length=100), nullable=True),
    sa.Column('mandi_raw', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('arrivals_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'crop', 'variety', 'grade', 'price_date')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sabhas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_code', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('user_status', sa.String(length=20), nullable=False),
    sa.Column('actual_price_per_q', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_code')
    )
    op.create_table('voice_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('stt_count', sa.Integer(), nullable=False),
    sa.Column('tts_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    op.create_table('sabha_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sabha_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sabha_id'], ['sabhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sabha_events_sabha_id'), 'sabha_events', ['sabha_id'], unique=False)
    op.create_index('ix_sabha_events_sabha_seq', 'sabha_events', ['sabha_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sabha_events_sabha_seq', table_name='sabha_events')
    op.drop_index(op.f('ix_sabha_events_sabha_id'), table_name='sabha_events')
    op.drop_table('sabha_events')
    op.drop_table('voice_usage')
    op.drop_table('sabhas')
    op.drop_table('refresh_tokens')
    op.drop_table('price_records')
    op.drop_table('users')
    op.drop_table('tts_cache')
    op.drop_index(op.f('ix_otp_challenges_mobile'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_table('mandis')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
